modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="dragons" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Dragons Mod" #mandatory

logoFile="examplemod.png" #optional
credits="Thanks to Delaney for being cool and creative" #optional
authors="Love, Cheese and small house plants" #optional

description='''
Trying to make a dragon mod for fun
'''

[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
